name: Infracost Comment

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  infracost:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Infracost
        run: |
          curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh

      - name: Run Infracost
        run: |
          infracost breakdown --path=${{ inputs['working-directory'] }} --format=json --out-file=infracost.json
          infracost comment github --path=infracost.json --repo=$GITHUB_REPOSITORY --github-token=${{ secrets.GITHUB_TOKEN }}