name: Terraform Linting

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Install linters
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          pip install --no-cache-dir checkov

      - name: Run tflint
        run: |
          cd ${{ inputs.working-directory }}
          tflint --init
          tflint

      - name: Run checkov
        run: |
          checkov -d ${{ inputs.working-directory }}